#!/bin/bash

SOURCE=$1
MASTERS=$2
NVALUE=$3
mkdir -p $MASTERS

COUNTER=1
while [  $COUNTER -le "$3" ]; do
####### create dictionary files for all texts
echo "Now processing ngrams of length $COUNTER..."

for f in $SOURCE/*.$COUNTER.ngram
do
cat "$f" >> $MASTERS/$COUNTER.master.txt
echo "Added $f to master unsorted list"
done

COUNTER=$((COUNTER+1))
done

## finished creating unsorted master lists, now created unique sorted masters
echo "Master lists have been created."


